import "./globals.css";

export const metadata = {
  title: {
    absolute:"",
    default:"Nextjs Practice",
    template:"%s | Sahil Kadge", //%s replace the meta data title of that page look for blog page
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <header
        style={{
          backgroundColor:"lightblue",
          padding:"1rem",
        }}
      >
        <p>Header</p>
      </header>
      
      {children}

      <footer
        style={{
          backgroundColor:"ghostwhite",
          padding:"1rem",
        }} 
      >
        <p>footer</p>
      </footer>
      
      </body>
      
    </html>
  )
}
